version: '3'
services:
  chrome-container:
    container_name: chrome-container
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  simplescraperapi:
    # build: .
    image: phillipdenness1/simplescraperapi
    ports:
      - "5000:5000"
    environment:
      - CHROME_DRIVER_PATH="/usr/local/bin/chromedriver"
      - SELENIUM_URL=chrome-container
      - SELENIUM_PORT=4444
    links:
      - chrome-container
    depends_on:
      - chrome-container

