spring:
  application:
    name: SimpleScraperApi
server:
  port: ${PORT:5000}
  connection-timeout: ${CONTOLLER_TIMEOUT:10}
app:
  selenium:
    geckodriverPath: ${GECKODRIVER_PATH:C:\\bin\\geckodriver.exe}
    chromeDriverPath: ${CHROME_DRIVER_PATH:C:\\bin\\chromedriver.exe}
    chromeBinary: ${CHROME_BINARY:""}
    firefoxBinary: ${FIREFOX_BINARY:""}
    iterationsBeforeRestart: ${ITERATIONS_BROWSER:3}
  controller:
    timeout: ${CONTOLLER_TIMEOUT:10}
