spring:
  application:
    name: SimpleScraperApi
server:
  port: ${PORT:5000}
selenium:
  timeout_seconds: ${TIMEOUT_SECONDS:10}
  chrome_driver_path: ${CHROME_DRIVER_PATH:/usr/bin/chromedriver}
  selenium_url: ${SELENIUM_URL:hub}
  selenium_port: ${SELENIUM_PORT:4444}

