spring:
  application:
    name: SimpleScraperApi
server:
  port: ${PORT:5000}
selenium:
  aviva_credentials: ${AVIVA_CREDS:username password,username2 password2}
authentication:
  token_expiration: ${EXPIRATION_TIME:1440}
  signing_key: ${SIGNING_KEY}
