
#server:
#  ssl:
#    key-store: classpath:server.p12
#    key-store-password: simplescraperapi
#    key-store-type: PKCS12
#    key-alias: pdenness-simple-scraper-api.us-east-1.elasticbeanstalk.com
#  port: ${SERVER_PORT:5001}
spring:
  application:
    name: SimpleScraperApi
